import type {
  AiArtifactIdentity,
  AiEngineeringAuthority,
  AiInternetRetrievalStatus,
  AiLocalRetrievalStatus,
  AiSseEvent,
} from '../../types/domain'

export type AiRunState =
  | 'idle'
  | 'connecting'
  | 'checking'
  | 'streaming'
  | 'complete'
  | 'partial'
  | 'cancelled'
  | 'offline'
  | 'error'

export type AiSourceKind =
  | 'local-model'
  | 'deterministic-tools'
  | 'project-context'
  | 'local-docs'
  | 'internet-evidence'
  | 'fallback'

export type AiSourceBadge = {
  detail: string
  kind: AiSourceKind
  label: string
}

export type AiRunMetadata = {
  artifact?: AiArtifactIdentity
  engineeringAuthority?: AiEngineeringAuthority
  fallbackReasonCode?: string
  fallbackUsed?: boolean
  internetRetrieval?: AiInternetRetrievalStatus
  localRetrieval?: AiLocalRetrievalStatus
  mode?: AiSseEvent['mode']
  model?: AiSseEvent['model']
  projectRevision?: string
}

export type AiRunPresentation = {
  detail: string
  label: string
}

export type AiUncertainty = {
  level?: string
  missingEvidence?: string[]
  reasonCode?: string
}

export function classifyAiStart(mode?: AiSseEvent['mode']): AiRunState {
  if (mode === 'unavailable') return 'offline'
  if (mode === 'deterministic-fallback') return 'checking'
  return 'streaming'
}

export function classifyAiTerminal(
  eventType: string,
  code: string | undefined,
  contentCharacters: number,
): AiRunState {
  if (eventType === 'complete') return 'complete'
  if (code === 'REQUEST_CANCELLED' || code === 'CLIENT_DISCONNECTED') return 'cancelled'
  if (contentCharacters > 0) return 'partial'
  if (code && /GATEWAY|SERVICE|OFFLINE|UNAVAILABLE|TIMEOUT/.test(code)) return 'offline'
  return 'error'
}

export function describeAiRun(state: AiRunState, metadata: AiRunMetadata = {}): AiRunPresentation {
  const fallbackDetail = metadata.fallbackUsed || metadata.mode === 'deterministic-fallback'
    ? 'Deterministic VoltForge engineering tools are active; no release-approved neural artifact is active.'
    : 'Generated by the private VoltForge local AI service.'

  switch (state) {
    case 'connecting':
      return { label: 'Connecting', detail: 'Starting the local VoltForge AI service.' }
    case 'checking':
      if (metadata.artifact?.runtimeState === 'warming' || metadata.artifact?.runtimeState === 'loading') {
        return { label: 'Warming local AI', detail: 'The local VoltForge artifact is warming before engineering checks run.' }
      }
      return { label: 'Running engineering checks', detail: fallbackDetail }
    case 'streaming':
      return { label: 'Generating response', detail: fallbackDetail }
    case 'complete':
      return { label: 'Response ready', detail: 'Review the evidence and proposed changes before using them.' }
    case 'partial':
      return { label: 'Partial response', detail: 'The response stopped before completion. Review it before using it.' }
    case 'cancelled':
      return { label: 'Canceled', detail: 'The response was canceled. No project changes were made.' }
    case 'offline':
      return { label: 'Local AI unavailable', detail: 'The local AI or gateway is unavailable. Project editing remains available.' }
    case 'error':
      return { label: 'Response error', detail: 'The local VoltForge response could not complete. Try again.' }
    default:
      return { label: 'Ready', detail: 'Ask about the current circuit, firmware, or simulation.' }
  }
}

export function safeAiErrorMessage(code?: string): string {
  switch (code) {
    case 'AI_PROJECT_REVISION_STALE':
      return 'The project changed while this request was prepared. Refresh the project and try again.'
    case 'AI_PROJECT_ACCESS_DENIED':
      return 'This project is not available in the current account.'
    case 'AI_USER_STREAM_LIMIT':
    case 'AI_PROJECT_STREAM_LIMIT':
      return 'Another VoltForge AI response is already active. Try again when it finishes.'
    case 'REQUEST_TIMEOUT':
      return 'The local AI response took too long. No project changes were made.'
    case 'REQUEST_CANCELLED':
    case 'CLIENT_DISCONNECTED':
      return 'The response was canceled. No project changes were made.'
    case 'API_REQUEST_TOO_LARGE':
    case 'AI_REQUEST_LIMIT_REACHED':
      return 'This AI request is too large. Reduce the selected context and try again.'
    default:
      return 'The local VoltForge AI response is temporarily unavailable. Your project was not changed.'
  }
}

export function collectAiSources(metadata: AiRunMetadata = {}): AiSourceBadge[] {
  const sources: AiSourceBadge[] = []
  const add = (badge: AiSourceBadge) => {
    if (!sources.some((item) => item.kind === badge.kind)) sources.push(badge)
  }

  if (metadata.mode === 'neural-quality-gated') {
    add({ kind: 'local-model', label: 'VoltForge local model', detail: 'Private project-specific local inference.' })
  }
  if (metadata.mode === 'deterministic-fallback' || metadata.fallbackUsed) {
    add({
      kind: 'deterministic-tools',
      label: 'Deterministic engineering tools',
      detail: metadata.fallbackReasonCode
        ? `Fallback reason: ${metadata.fallbackReasonCode.replaceAll('_', ' ').toLowerCase()}.`
        : 'Bounded local rules and engineering checks.',
    })
  }
  if (metadata.projectRevision) {
    add({
      kind: 'project-context',
      label: 'Current project snapshot',
      detail: `Bound to project revision ${metadata.projectRevision}.`,
    })
  }
  if (metadata.localRetrieval && metadata.localRetrieval.status !== 'unavailable') {
    add({
      kind: 'local-docs',
      label: 'Local engineering knowledge',
      detail: metadata.localRetrieval.returnedCount > 0
        ? `${metadata.localRetrieval.returnedCount} bounded local result(s) selected.`
        : 'No matching local knowledge was selected.',
    })
  }
  if (metadata.internetRetrieval && metadata.internetRetrieval.status !== 'not-requested') {
    const status = metadata.internetRetrieval.status
    add({
      kind: 'internet-evidence',
      label: 'Internet evidence',
      detail: status === 'complete'
        ? `${metadata.internetRetrieval.returnedCount} untrusted web result(s) selected.`
        : `Web retrieval ${status}; it is not required for local generation.`,
    })
  }
  if (metadata.mode === 'unavailable') {
    add({ kind: 'fallback', label: 'Unavailable local AI', detail: 'No local model response was available.' })
  }
  return sources
}
