import type { ElectronicComponent } from '../../types/domain';
import { BOARD_CATALOG } from './boardCatalog';
import { SIMULATION_MODELS } from '../simulator/simulationModels';

const makeComponent = (
  component: Omit<ElectronicComponent, 'createdAt' | 'isPremium' | 'sortOrder'> & { sortOrder?: number }
): ElectronicComponent => ({
  createdAt: '',
  isPremium: false,
  sortOrder: component.sortOrder ?? 50,
  ...component,
});

export const catalogBoardComponents: ElectronicComponent[] = BOARD_CATALOG.map((board) => ({
  category: 'BOARD',
  createdAt: '',
  defaultProperties: {
    clockSpeed: board.clock,
    compilerSupport: board.compiler,
    family: board.family,
    features: board.features,
    logicVoltage: board.logicVoltage,
  },
  description: `${board.family} board with ${board.features.join(', ')}.`,
  id: `catalog_${board.type}`,
  isPremium: false,
  name: board.name,
  pinConfig: { footprint: board.footprint, pinProfile: board.type },
  sortOrder: board.sortOrder,
  type: board.type,
}));

export const builtinCanvasComponents: ElectronicComponent[] = [
  ...catalogBoardComponents,
  makeComponent({
    id: 'catalog_resistor',
    name: 'Resistor',
    type: 'RESISTOR',
    category: 'PASSIVE',
    description: 'Two-terminal resistor for current limiting and dividers',
    defaultProperties: { resistance: 1000 },
    pinConfig: { pinProfile: 'RESISTOR' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_capacitor',
    name: 'Capacitor',
    type: 'CAPACITOR',
    category: 'PASSIVE',
    description: 'Generic two-terminal capacitor',
    defaultProperties: { capacitance: 0.000001 },
    pinConfig: { pinProfile: 'CAPACITOR' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_ceramic_capacitor',
    name: 'Ceramic Capacitor',
    type: 'CERAMIC_CAPACITOR',
    category: 'PASSIVE',
    description: 'Non-polarized ceramic capacitor',
    defaultProperties: { capacitance: 0.0000001 },
    pinConfig: { pinProfile: 'CERAMIC_CAPACITOR' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_electrolytic_capacitor',
    name: 'Electrolytic Capacitor',
    type: 'ELECTROLYTIC_CAPACITOR',
    category: 'PASSIVE',
    description: 'Polarized electrolytic capacitor',
    defaultProperties: { capacitance: 0.00001 },
    pinConfig: { pinProfile: 'ELECTROLYTIC_CAPACITOR' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_diode',
    name: 'Diode',
    type: 'DIODE',
    category: 'PASSIVE',
    description: 'Directional semiconductor diode',
    defaultProperties: { forwardVoltage: 0.7 },
    pinConfig: { pinProfile: 'DIODE' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_zener_diode',
    name: 'Zener Diode',
    type: 'ZENER_DIODE',
    category: 'PASSIVE',
    description: 'Reverse-breakdown reference and voltage clamp diode',
    defaultProperties: { forwardVoltage: 0.7, zenerVoltage: 5.1, zenerResistance: 8 },
    pinConfig: { pinProfile: 'DIODE' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_schottky_diode',
    name: 'Schottky Diode',
    type: 'SCHOTTKY_DIODE',
    category: 'PASSIVE',
    description: 'Low-forward-voltage fast diode',
    defaultProperties: { forwardVoltage: 0.3 },
    pinConfig: { pinProfile: 'DIODE' },
    sortOrder: 7,
  }),
  makeComponent({
    id: 'catalog_inductor',
    name: 'Inductor',
    type: 'INDUCTOR',
    category: 'PASSIVE',
    description: 'Two-terminal energy storage inductor',
    defaultProperties: { inductance: 0.01 },
    pinConfig: { pinProfile: 'INDUCTOR' },
    sortOrder: 8,
  }),
  makeComponent({
    id: 'catalog_transformer',
    name: 'Transformer',
    type: 'TRANSFORMER',
    category: 'POWER',
    description: 'Coupled primary and secondary windings with configurable turns ratio',
    defaultProperties: {
      primaryInductance: SIMULATION_MODELS.transformer.primaryInductance_H,
      turnsRatio: SIMULATION_MODELS.transformer.turnsRatio,
      coupling: SIMULATION_MODELS.transformer.coupling,
    },
    pinConfig: { pinProfile: 'TRANSFORMER' },
    sortOrder: 8.5,
  }),
  makeComponent({
    id: 'catalog_variable_capacitor',
    name: 'Variable Capacitor',
    type: 'VARIABLE_CAPACITOR',
    category: 'PASSIVE',
    description: 'Adjustable two-terminal capacitor',
    defaultProperties: { capacitance: 100e-12 },
    pinConfig: { pinProfile: 'CAPACITOR' },
    sortOrder: 9,
  }),
  makeComponent({
    id: 'catalog_thermistor',
    name: 'NTC Thermistor',
    type: 'THERMISTOR_NTC',
    category: 'PASSIVE',
    description: 'Temperature-dependent resistor using the beta model',
    defaultProperties: { nominalResistance: 10000, nominalTemperature_C: 25, beta: 3950, temperature_C: 25 },
    pinConfig: { pinProfile: 'THERMISTOR_NTC' },
    sortOrder: 10,
  }),
  makeComponent({
    id: 'catalog_nmos',
    name: 'N-Channel MOSFET',
    type: 'NMOS',
    category: 'PASSIVE',
    description: 'Voltage-controlled low-side enhancement switch',
    defaultProperties: { thresholdVoltage: 2, onResistance: 0.08, offResistance: 100000000 },
    pinConfig: { pinProfile: 'NMOS' },
    sortOrder: 11,
  }),
  makeComponent({
    id: 'catalog_pmos',
    name: 'P-Channel MOSFET',
    type: 'PMOS',
    category: 'PASSIVE',
    description: 'Voltage-controlled high-side enhancement switch',
    defaultProperties: { thresholdVoltage: 2, onResistance: 0.08, offResistance: 100000000 },
    pinConfig: { pinProfile: 'PMOS' },
    sortOrder: 12,
  }),
  makeComponent({
    id: 'catalog_bridge_rectifier',
    name: 'Bridge Rectifier',
    type: 'BRIDGE_RECTIFIER',
    category: 'POWER',
    description: 'Four-diode full-wave bridge rectifier',
    defaultProperties: { forwardVoltage: 0.7 },
    pinConfig: { pinProfile: 'BRIDGE_RECTIFIER' },
    sortOrder: 13,
  }),
  makeComponent({
    id: 'catalog_opamp_ideal',
    name: 'Ideal Op-Amp',
    type: 'OPAMP_IDEAL',
    category: 'PASSIVE',
    description: 'High-gain saturated voltage-controlled amplifier',
    defaultProperties: { openLoopGain: 100000, outputLow: 0, outputHigh: 5 },
    pinConfig: { pinProfile: 'OPAMP_IDEAL' },
    sortOrder: 14,
  }),
  makeComponent({
    id: 'catalog_lm358',
    name: 'LM358 Op-Amp',
    type: 'OPAMP_LM358',
    category: 'PASSIVE',
    description: 'Single-channel educational LM358-style op-amp model',
    defaultProperties: { openLoopGain: 100000, outputLow: 0, outputHigh: 4.8 },
    pinConfig: { pinProfile: 'OPAMP_LM358' },
    sortOrder: 15,
  }),
  makeComponent({
    id: 'catalog_led_standard',
    name: 'Standard LED',
    type: 'LED_STANDARD',
    category: 'LED',
    description: 'Two-lead indicator LED',
    defaultProperties: { ledColor: 'red', forwardVoltage: 2.0 },
    pinConfig: { pinProfile: 'LED_STANDARD' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_led_rgb',
    name: 'RGB LED',
    type: 'LED_RGB',
    category: 'LED',
    description: 'Four-lead RGB indicator LED',
    defaultProperties: { ledColor: 'rgb' },
    pinConfig: { pinProfile: 'LED_RGB' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_7805',
    name: '7805 Voltage Regulator',
    type: 'VOLTAGE_REGULATOR_7805',
    category: 'POWER',
    description: 'Linear 5V voltage regulator with VIN, GND, and VOUT pins',
    defaultProperties: { voltage: 5 },
    pinConfig: { pinProfile: 'VOLTAGE_REGULATOR_7805' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_battery_9v',
    name: '9V Battery',
    type: 'BATTERY_9V',
    category: 'POWER',
    description: 'Standalone 9 V battery with positive and negative terminals',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.battery9V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_battery_aa',
    name: 'AA Battery',
    type: 'BATTERY_AA',
    category: 'POWER',
    description: 'Standalone 1.5 V AA cell with positive and negative terminals',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.batteryAA, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_supply_3v3',
    name: '3.3V DC Supply',
    type: 'DC_SOURCE_3V3',
    category: 'POWER',
    description: 'Regulated 3.3 V DC source with configurable enable state',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply3V3, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_supply_5v',
    name: '5V DC Supply',
    type: 'DC_SOURCE_5V',
    category: 'POWER',
    description: 'Regulated 5 V DC source with configurable output voltage',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply5V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_supply_12v',
    name: '12V DC Supply',
    type: 'DC_SOURCE_12V',
    category: 'POWER',
    description: 'Regulated 12 V DC source with configurable output voltage',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply12V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_power_supply',
    name: 'Configurable DC Supply',
    type: 'POWER_SUPPLY',
    category: 'POWER',
    description: 'Configurable DC voltage source for standalone circuits',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply5V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 7,
  }),
  makeComponent({
    id: 'catalog_function_generator',
    name: 'AC Function Generator',
    type: 'AC_FUNCTION_GENERATOR',
    category: 'POWER',
    description: 'Sine, square, or triangle source with configurable amplitude and frequency',
    defaultProperties: {
      amplitude: SIMULATION_MODELS.sources.acAmplitude,
      offset: 0,
      frequencyHz: SIMULATION_MODELS.sources.acFrequencyHz,
      waveform: 'sine',
      isOn: true,
    },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 8,
  }),
  makeComponent({
    id: 'catalog_ground',
    name: 'Ground',
    type: 'GROUND',
    category: 'POWER',
    description: 'Common 0 V reference net for the circuit',
    defaultProperties: {},
    pinConfig: { pinProfile: 'GROUND' },
    sortOrder: 9,
  }),
  makeComponent({
    id: 'catalog_motor_dc',
    name: 'DC Motor',
    type: 'MOTOR_DC',
    category: 'MOTOR',
    description: 'Two-terminal brushed DC motor with voltage-dependent shaft speed',
    defaultProperties: {
      ratedVoltage: SIMULATION_MODELS.dcMotor.ratedVoltage,
      ratedRpm: SIMULATION_MODELS.dcMotor.ratedRpm,
      windingResistance: SIMULATION_MODELS.dcMotor.windingResistance,
      startVoltage: SIMULATION_MODELS.dcMotor.startVoltage,
      startCurrent_A: SIMULATION_MODELS.dcMotor.startCurrent_A,
    },
    pinConfig: { pinProfile: 'MOTOR_DC' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_servo_motor',
    name: 'Servo Motor',
    type: 'SERVO_MOTOR',
    category: 'MOTOR',
    description: 'Powered PWM position servo with a 0–180 degree output shaft',
    defaultProperties: {
      minimumSupplyVoltage: SIMULATION_MODELS.servo.minimumSupplyVoltage,
      maximumSupplyVoltage: SIMULATION_MODELS.servo.maximumSupplyVoltage,
      angle: SIMULATION_MODELS.servo.minimumAngle,
    },
    pinConfig: { pinProfile: 'SERVO_MOTOR' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_stepper_motor',
    name: 'Stepper Motor',
    type: 'STEPPER_MOTOR',
    category: 'MOTOR',
    description: 'Four-coil stepper motor that advances from valid phase sequences',
    defaultProperties: {
      stepsPerRevolution: SIMULATION_MODELS.stepper.stepsPerRevolution,
      windingResistance: SIMULATION_MODELS.stepper.windingResistance,
      minimumPhaseCurrent_A: SIMULATION_MODELS.stepper.minimumPhaseCurrent_A,
    },
    pinConfig: { pinProfile: 'STEPPER_MOTOR' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_stepper_driver',
    name: 'ULN2003 Stepper Driver',
    type: 'MOTOR_STEPPER',
    category: 'MOTOR',
    description: 'ULN2003-style stepper module with VCC, GND, and four phase inputs',
    defaultProperties: {
      stepsPerRevolution: SIMULATION_MODELS.stepper.gearedStepsPerRevolution,
      windingResistance: SIMULATION_MODELS.stepper.windingResistance,
      minimumPhaseCurrent_A: SIMULATION_MODELS.stepper.minimumPhaseCurrent_A,
    },
    pinConfig: { pinProfile: 'MOTOR_STEPPER' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_esc_module',
    name: 'Brushless ESC',
    type: 'ESC_MODULE',
    category: 'MOTOR',
    description: 'PWM-controlled electronic speed controller with three phase outputs',
    defaultProperties: { outputVoltage: SIMULATION_MODELS.bldc.supplyVoltage, escPwm: 0 },
    pinConfig: { pinProfile: 'ESC_MODULE' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_bldc_motor',
    name: 'BLDC Motor',
    type: 'MOTOR_BLDC',
    category: 'MOTOR',
    description: 'Three-phase brushless motor load driven by an ESC',
    defaultProperties: {
      minimumSupplyVoltage: SIMULATION_MODELS.bldc.minimumSupplyVoltage,
      maximumRpm: SIMULATION_MODELS.bldc.maximumRpm,
      windingResistance: SIMULATION_MODELS.bldc.windingResistance,
    },
    pinConfig: { pinProfile: 'MOTOR_BLDC' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_buzzer',
    name: 'Buzzer',
    type: 'BUZZER',
    category: 'MOTOR',
    description: 'Current-driven buzzer with optional signal frequency',
    defaultProperties: { resistance: 42, frequency: SIMULATION_MODELS.audio.buzzerFrequencyHz },
    pinConfig: { pinProfile: 'BUZZER' },
    sortOrder: 7,
  }),
  makeComponent({
    id: 'catalog_neopixel',
    name: 'NeoPixel',
    type: 'LED_NEOPIXEL',
    category: 'LED',
    description: 'Addressable RGB pixel with power and data terminals',
    defaultProperties: { pixelCount: 1, brightness: 30 },
    pinConfig: { pinProfile: 'LED_NEOPIXEL' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_push_button',
    name: 'Push Button',
    type: 'PUSH_BUTTON',
    category: 'PASSIVE',
    description: 'Momentary tactile switch',
    defaultProperties: { pressed: false },
    pinConfig: { pinProfile: 'PUSH_BUTTON' },
    sortOrder: 8,
  }),
  makeComponent({
    id: 'catalog_switch_spst',
    name: 'SPST Switch',
    type: 'SWITCH_SPST',
    category: 'PASSIVE',
    description: 'Latching single-pole single-throw switch',
    defaultProperties: { isClosed: false },
    pinConfig: { pinProfile: 'SWITCH_SPST' },
    sortOrder: 9,
  }),
  makeComponent({
    id: 'catalog_potentiometer',
    name: 'Potentiometer',
    type: 'POTENTIOMETER',
    category: 'PASSIVE',
    description: 'Three-terminal variable resistor',
    defaultProperties: { resistance: 10000, position: 0.5 },
    pinConfig: { pinProfile: 'POTENTIOMETER' },
    sortOrder: 10,
  }),
  ...([
    ['RELAY_SINGLE', 'Single Relay Module', 'RELAY', 'One-channel relay module with COM/NO/NC contacts'],
    ['RELAY_SPDT', 'SPDT Relay', 'RELAY', 'Bare SPDT relay with coil and changeover contacts'],
    ['RELAY_2CH', '2-Channel Relay Module', 'RELAY', 'Dual-channel relay module'],
    ['RELAY_4CH', '4-Channel Relay Module', 'RELAY', 'Four-channel relay module'],
  ] as const).map(([type, name, category, description], index) => makeComponent({
    id: `catalog_${type.toLowerCase()}`,
    name,
    type,
    category,
    description,
    defaultProperties: { triggerType: 'Active Low' },
    pinConfig: { pinProfile: type },
    sortOrder: 20 + index,
  })),
  ...([
    ['TEMP_SENSOR', 'Temperature Sensor', 'SENSOR', { temperature: SIMULATION_MODELS.sensors.dhtTemperature_C }],
    ['SENSOR_DHT11', 'DHT11 Temperature/Humidity', 'SENSOR', { temperature: SIMULATION_MODELS.sensors.dhtTemperature_C, humidity: SIMULATION_MODELS.sensors.dhtHumidity_percent }],
    ['SENSOR_DHT22', 'DHT22 Temperature/Humidity', 'SENSOR', { temperature: SIMULATION_MODELS.sensors.dhtTemperature_C, humidity: SIMULATION_MODELS.sensors.dhtHumidity_percent }],
    ['ULTRASONIC_SENSOR', 'Ultrasonic Sensor', 'SENSOR', { distance: SIMULATION_MODELS.sensors.ultrasonicDistance_cm }],
    ['SENSOR_ULTRASONIC', 'Ultrasonic Sensor', 'SENSOR', { distance: SIMULATION_MODELS.sensors.ultrasonicDistance_cm }],
    ['PIR_SENSOR', 'PIR Motion Sensor', 'SENSOR', { motionDetected: false }],
    ['SENSOR_PIR', 'PIR Motion Sensor', 'SENSOR', { motionDetected: false }],
    ['LDR', 'Photoresistor', 'SENSOR', { lightLevel: 50 }],
    ['SENSOR_LDR', 'Light Sensor', 'SENSOR', { lightLevel: 50 }],
    ['SOIL_MOISTURE', 'Soil Moisture Sensor', 'SENSOR', { moistureLevel: SIMULATION_MODELS.sensors.soilMoisture_percent }],
    ['SENSOR_IMU', '6-Axis IMU', 'SENSOR', { accelerationX: 0, accelerationY: 0, accelerationZ: 1, gyroX: 0, gyroY: 0, gyroZ: 0 }],
  ] as const).map(([type, name, category, defaultProperties], index) => makeComponent({
    id: `catalog_${type.toLowerCase()}`,
    name,
    type,
    category,
    description: `${name} with user-controlled environmental stimulus properties`,
    defaultProperties,
    pinConfig: { pinProfile: type },
    sortOrder: 40 + index,
  })),
  ...([
    ['LCD_16X2', 'LCD 16x2', 'DISPLAY'],
    ['DISPLAY_LCD_I2C', 'I2C LCD 16x2', 'DISPLAY'],
    ['OLED_DISPLAY', 'OLED Display', 'DISPLAY'],
    ['DISPLAY_OLED', 'I2C OLED Display', 'DISPLAY'],
    ['DISPLAY_7SEG', '7-Segment Display', 'DISPLAY'],
  ] as const).map(([type, name, category], index) => makeComponent({
    id: `catalog_${type.toLowerCase()}`,
    name,
    type,
    category,
    description: `${name} with power-aware visual output`,
    defaultProperties: {},
    pinConfig: { pinProfile: type },
    sortOrder: 60 + index,
  })),
  ...([
    ['BLUETOOTH_MODULE', 'Bluetooth Module'],
    ['WIFI_MODULE', 'Wi-Fi Module'],
    ['IR_RECEIVER', 'IR Receiver'],
    ['RC_RECEIVER', 'RC Receiver'],
  ] as const).map(([type, name], index) => makeComponent({
    id: `catalog_${type.toLowerCase()}`,
    name,
    type,
    category: 'COMMUNICATION',
    description: `${name} with power-aware communication pins`,
    defaultProperties: {},
    pinConfig: { pinProfile: type },
    sortOrder: 70 + index,
  })),
  makeComponent({
    id: 'catalog_breadboard',
    name: 'Breadboard',
    type: 'BREADBOARD',
    category: 'PASSIVE',
    description: 'Half-size solderless breadboard with rails and terminal strips',
    defaultProperties: {},
    pinConfig: { pinProfile: 'BREADBOARD' },
    sortOrder: 10,
  }),
  makeComponent({
    id: 'catalog_555_timer',
    name: 'NE555 Timer',
    type: 'IC_555_TIMER',
    category: 'LOGIC',
    description: '555 timer IC for monostable and astable oscillator circuits',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP8', pinProfile: 'IC_555_TIMER' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_74hc595',
    name: '74HC595 Shift Register',
    type: 'IC_74HC595',
    category: 'LOGIC',
    description: '8-bit serial-in parallel-out shift register with output latches',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC595' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_74hc165',
    name: '74HC165 Shift Register',
    type: 'IC_74HC165',
    category: 'LOGIC',
    description: '8-bit parallel-in serial-out shift register',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC165' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_74hc138',
    name: '74HC138 3-to-8 Decoder',
    type: 'IC_74HC138',
    category: 'LOGIC',
    description: '3-to-8 line inverting decoder and demultiplexer',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC138' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_74hc151',
    name: '74HC151 8-Ch Multiplexer',
    type: 'IC_74HC151',
    category: 'LOGIC',
    description: '8-channel data selector and multiplexer',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC151' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_cd4017',
    name: 'CD4017 Decade Counter',
    type: 'IC_CD4017',
    category: 'LOGIC',
    description: 'Johnson decade counter with 10 decoded outputs',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_CD4017' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_multimeter',
    name: 'Digital Multimeter',
    type: 'MULTIMETER',
    category: 'INSTRUMENT',
    description: 'Dual-probe voltage, current, and resistance measurement tool',
    defaultProperties: { mode: 'VOLTAGE' },
    pinConfig: { footprint: 'MODULE', pinProfile: 'MULTIMETER' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_oscilloscope',
    name: 'Digital Oscilloscope',
    type: 'OSCILLOSCOPE',
    category: 'INSTRUMENT',
    description: '2-channel real-time waveform capture and frequency analyzer',
    defaultProperties: { timebase: '1ms', voltsPerDiv: 1.0 },
    pinConfig: { footprint: 'MODULE', pinProfile: 'OSCILLOSCOPE' },
    sortOrder: 2,
  }),
];

const builtinByType = new Map(builtinCanvasComponents.map((component) => [component.type, component]));

export function findCatalogComponent(type: string): ElectronicComponent | undefined {
  return builtinByType.get(type);
}

export function mergeComponentLibrary(apiComponents: ElectronicComponent[] = []): ElectronicComponent[] {
  const byType = new Map<string, ElectronicComponent>();
  builtinCanvasComponents.forEach((component) => byType.set(component.type, component));
  apiComponents.forEach((component) => byType.set(component.type, component));
  return Array.from(byType.values());
}
