import type { ElectronicComponent } from '../../types/domain';
import { BOARD_CATALOG } from './boardCatalog';
import { SIMULATION_MODELS } from '../simulator/simulationModels';

const makeComponent = (
  component: Omit<ElectronicComponent, 'createdAt' | 'isPremium' | 'sortOrder'> & { sortOrder?: number }
): ElectronicComponent => ({
  createdAt: '',
  isPremium: false,
  sortOrder: component.sortOrder ?? 50,
  ...component,
});

export const catalogBoardComponents: ElectronicComponent[] = BOARD_CATALOG.map((board) => ({
  category: 'BOARD',
  createdAt: '',
  defaultProperties: {
    clockSpeed: board.clock,
    compilerSupport: board.compiler,
    canvasArtworkStatus: board.geometry.artworkStatus,
    canvasGeometryRevision: board.geometry.geometryRevision,
    canvasPinoutStatus: board.geometry.pinoutStatus,
    family: board.family,
    features: board.features,
    logicVoltage: board.logicVoltage,
  },
  description: `${board.family} board with ${board.features.join(', ')}.`,
  id: `catalog_${board.type}`,
  isPremium: false,
  name: board.name,
  pinConfig: { footprint: board.footprint, pinProfile: board.type },
  sortOrder: board.sortOrder,
  type: board.type,
}));

export const builtinCanvasComponents: ElectronicComponent[] = [
  ...catalogBoardComponents,
  makeComponent({
    id: 'catalog_resistor',
    name: 'Resistor',
    type: 'RESISTOR',
    category: 'PASSIVE',
    description: 'Two-terminal resistor for current limiting and dividers',
    defaultProperties: { resistance: 1000 },
    pinConfig: { pinProfile: 'RESISTOR' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_capacitor',
    name: 'Capacitor',
    type: 'CAPACITOR',
    category: 'PASSIVE',
    description: 'Generic two-terminal capacitor',
    defaultProperties: { capacitance: 0.000001 },
    pinConfig: { pinProfile: 'CAPACITOR' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_ceramic_capacitor',
    name: 'Ceramic Capacitor',
    type: 'CERAMIC_CAPACITOR',
    category: 'PASSIVE',
    description: 'Non-polarized ceramic capacitor',
    defaultProperties: { capacitance: 0.0000001 },
    pinConfig: { pinProfile: 'CERAMIC_CAPACITOR' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_electrolytic_capacitor',
    name: 'Electrolytic Capacitor',
    type: 'ELECTROLYTIC_CAPACITOR',
    category: 'PASSIVE',
    description: 'Polarized electrolytic capacitor',
    defaultProperties: { capacitance: 0.00001 },
    pinConfig: { pinProfile: 'ELECTROLYTIC_CAPACITOR' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_diode',
    name: 'Diode',
    type: 'DIODE',
    category: 'PASSIVE',
    description: 'Directional semiconductor diode',
    defaultProperties: { forwardVoltage: 0.7 },
    pinConfig: { pinProfile: 'DIODE' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_zener_diode',
    name: 'Zener Diode',
    type: 'ZENER_DIODE',
    category: 'PASSIVE',
    description: 'Reverse-breakdown reference and voltage clamp diode',
    defaultProperties: { forwardVoltage: 0.7, zenerVoltage: 5.1, zenerResistance: 8 },
    pinConfig: { pinProfile: 'DIODE' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_schottky_diode',
    name: 'Schottky Diode',
    type: 'SCHOTTKY_DIODE',
    category: 'PASSIVE',
    description: 'Low-forward-voltage fast diode',
    defaultProperties: { forwardVoltage: 0.3 },
    pinConfig: { pinProfile: 'DIODE' },
    sortOrder: 7,
  }),
  makeComponent({
    id: 'catalog_inductor',
    name: 'Inductor',
    type: 'INDUCTOR',
    category: 'PASSIVE',
    description: 'Two-terminal energy storage inductor',
    defaultProperties: { inductance: 0.01 },
    pinConfig: { pinProfile: 'INDUCTOR' },
    sortOrder: 8,
  }),
  makeComponent({
    id: 'catalog_transformer',
    name: 'Transformer',
    type: 'TRANSFORMER',
    category: 'POWER',
    description: 'Coupled primary and secondary windings with configurable turns ratio',
    defaultProperties: {
      primaryInductance: SIMULATION_MODELS.transformer.primaryInductance_H,
      turnsRatio: SIMULATION_MODELS.transformer.turnsRatio,
      coupling: SIMULATION_MODELS.transformer.coupling,
    },
    pinConfig: { pinProfile: 'TRANSFORMER' },
    sortOrder: 8.5,
  }),
  makeComponent({
    id: 'catalog_variable_capacitor',
    name: 'Variable Capacitor',
    type: 'VARIABLE_CAPACITOR',
    category: 'PASSIVE',
    description: 'Adjustable two-terminal capacitor',
    defaultProperties: { capacitance: 100e-12 },
    pinConfig: { pinProfile: 'CAPACITOR' },
    sortOrder: 9,
  }),
  makeComponent({
    id: 'catalog_thermistor',
    name: 'NTC Thermistor',
    type: 'THERMISTOR_NTC',
    category: 'PASSIVE',
    description: 'Temperature-dependent resistor using the beta model',
    defaultProperties: { nominalResistance: 10000, nominalTemperature_C: 25, beta: 3950, temperature_C: 25 },
    pinConfig: { pinProfile: 'THERMISTOR_NTC' },
    sortOrder: 10,
  }),
  makeComponent({
    id: 'catalog_nmos',
    name: 'N-Channel MOSFET',
    type: 'NMOS',
    category: 'PASSIVE',
    description: 'Voltage-controlled low-side enhancement switch',
    defaultProperties: { thresholdVoltage: 2, onResistance: 0.08, offResistance: 100000000 },
    pinConfig: { pinProfile: 'NMOS' },
    sortOrder: 11,
  }),
  makeComponent({
    id: 'catalog_pmos',
    name: 'P-Channel MOSFET',
    type: 'PMOS',
    category: 'PASSIVE',
    description: 'Voltage-controlled high-side enhancement switch',
    defaultProperties: { thresholdVoltage: 2, onResistance: 0.08, offResistance: 100000000 },
    pinConfig: { pinProfile: 'PMOS' },
    sortOrder: 12,
  }),
  makeComponent({
    id: 'catalog_bridge_rectifier',
    name: 'Bridge Rectifier',
    type: 'BRIDGE_RECTIFIER',
    category: 'POWER',
    description: 'Four-diode full-wave bridge rectifier',
    defaultProperties: { forwardVoltage: 0.7 },
    pinConfig: { pinProfile: 'BRIDGE_RECTIFIER' },
    sortOrder: 13,
  }),
  makeComponent({
    id: 'catalog_opamp_ideal',
    name: 'Ideal Op-Amp',
    type: 'OPAMP_IDEAL',
    category: 'PASSIVE',
    description: 'High-gain saturated voltage-controlled amplifier',
    defaultProperties: { openLoopGain: 100000, outputLow: 0, outputHigh: 5 },
    pinConfig: { pinProfile: 'OPAMP_IDEAL' },
    sortOrder: 14,
  }),
  makeComponent({
    id: 'catalog_lm358',
    name: 'LM358 Op-Amp',
    type: 'OPAMP_LM358',
    category: 'PASSIVE',
    description: 'Single-channel educational LM358-style op-amp model',
    defaultProperties: { openLoopGain: 100000, outputLow: 0, outputHigh: 4.8 },
    pinConfig: { pinProfile: 'OPAMP_LM358' },
    sortOrder: 15,
  }),
  makeComponent({
    id: 'catalog_led_standard',
    name: 'Standard LED',
    type: 'LED_STANDARD',
    category: 'LED',
    description: 'Two-lead indicator LED',
    defaultProperties: { ledColor: 'red', forwardVoltage: 2.0 },
    pinConfig: { pinProfile: 'LED_STANDARD' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_led_rgb',
    name: 'RGB LED',
    type: 'LED_RGB',
    category: 'LED',
    description: 'Four-lead RGB indicator LED',
    defaultProperties: { ledColor: 'rgb' },
    pinConfig: { pinProfile: 'LED_RGB' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_7805',
    name: '7805 Voltage Regulator',
    type: 'VOLTAGE_REGULATOR_7805',
    category: 'POWER',
    description: 'Linear 5V voltage regulator with VIN, GND, and VOUT pins',
    defaultProperties: { voltage: 5 },
    pinConfig: { pinProfile: 'VOLTAGE_REGULATOR_7805' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_battery_9v',
    name: '9V Battery',
    type: 'BATTERY_9V',
    category: 'POWER',
    description: 'Standalone 9 V battery with positive and negative terminals',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.battery9V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_battery_aa',
    name: 'AA Battery',
    type: 'BATTERY_AA',
    category: 'POWER',
    description: 'Standalone 1.5 V AA cell with positive and negative terminals',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.batteryAA, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_supply_3v3',
    name: '3.3V DC Supply',
    type: 'DC_SOURCE_3V3',
    category: 'POWER',
    description: 'Regulated 3.3 V DC source with configurable enable state',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply3V3, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_supply_5v',
    name: '5V DC Supply',
    type: 'DC_SOURCE_5V',
    category: 'POWER',
    description: 'Regulated 5 V DC source with configurable output voltage',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply5V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_supply_12v',
    name: '12V DC Supply',
    type: 'DC_SOURCE_12V',
    category: 'POWER',
    description: 'Regulated 12 V DC source with configurable output voltage',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply12V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_power_supply',
    name: 'Configurable DC Supply',
    type: 'POWER_SUPPLY',
    category: 'POWER',
    description: 'Configurable DC voltage source for standalone circuits',
    defaultProperties: { voltage: SIMULATION_MODELS.sources.supply5V, isOn: true },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 7,
  }),
  makeComponent({
    id: 'catalog_function_generator',
    name: 'AC Function Generator',
    type: 'AC_FUNCTION_GENERATOR',
    category: 'POWER',
    description: 'Sine, square, or triangle source with configurable amplitude and frequency',
    defaultProperties: {
      amplitude: SIMULATION_MODELS.sources.acAmplitude,
      offset: 0,
      frequencyHz: SIMULATION_MODELS.sources.acFrequencyHz,
      waveform: 'sine',
      isOn: true,
    },
    pinConfig: { pinProfile: 'POWER_SOURCE' },
    sortOrder: 8,
  }),
  makeComponent({
    id: 'catalog_ground',
    name: 'Ground',
    type: 'GROUND',
    category: 'POWER',
    description: 'Common 0 V reference net for the circuit',
    defaultProperties: {},
    pinConfig: { pinProfile: 'GROUND' },
    sortOrder: 9,
  }),
  makeComponent({
    id: 'catalog_motor_dc',
    name: 'DC Motor',
    type: 'MOTOR_DC',
    category: 'MOTOR',
    description: 'Two-terminal brushed DC motor with voltage-dependent shaft speed',
    defaultProperties: {
      ratedVoltage: SIMULATION_MODELS.dcMotor.ratedVoltage,
      ratedRpm: SIMULATION_MODELS.dcMotor.ratedRpm,
      windingResistance: SIMULATION_MODELS.dcMotor.windingResistance,
      startVoltage: SIMULATION_MODELS.dcMotor.startVoltage,
      startCurrent_A: SIMULATION_MODELS.dcMotor.startCurrent_A,
    },
    pinConfig: { pinProfile: 'MOTOR_DC' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_servo_motor',
    name: 'Servo Motor',
    type: 'SERVO_MOTOR',
    category: 'MOTOR',
    description: 'Powered PWM position servo with a 0–180 degree output shaft',
    defaultProperties: {
      minimumSupplyVoltage: SIMULATION_MODELS.servo.minimumSupplyVoltage,
      maximumSupplyVoltage: SIMULATION_MODELS.servo.maximumSupplyVoltage,
      angle: SIMULATION_MODELS.servo.minimumAngle,
    },
    pinConfig: { pinProfile: 'SERVO_MOTOR' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_stepper_motor',
    name: 'Stepper Motor',
    type: 'STEPPER_MOTOR',
    category: 'MOTOR',
    description: 'Four-coil stepper motor that advances from valid phase sequences',
    defaultProperties: {
      stepsPerRevolution: SIMULATION_MODELS.stepper.stepsPerRevolution,
      windingResistance: SIMULATION_MODELS.stepper.windingResistance,
      minimumPhaseCurrent_A: SIMULATION_MODELS.stepper.minimumPhaseCurrent_A,
    },
    pinConfig: { pinProfile: 'STEPPER_MOTOR' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_stepper_driver',
    name: 'ULN2003 Stepper Driver',
    type: 'MOTOR_STEPPER',
    category: 'MOTOR',
    description: 'ULN2003-style stepper module with VCC, GND, and four phase inputs',
    defaultProperties: {
      stepsPerRevolution: SIMULATION_MODELS.stepper.gearedStepsPerRevolution,
      windingResistance: SIMULATION_MODELS.stepper.windingResistance,
      minimumPhaseCurrent_A: SIMULATION_MODELS.stepper.minimumPhaseCurrent_A,
    },
    pinConfig: { pinProfile: 'MOTOR_STEPPER' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_esc_module',
    name: 'Brushless ESC',
    type: 'ESC_MODULE',
    category: 'MOTOR',
    description: 'PWM-controlled electronic speed controller with three phase outputs',
    defaultProperties: { outputVoltage: SIMULATION_MODELS.bldc.supplyVoltage, escPwm: 0 },
    pinConfig: { pinProfile: 'ESC_MODULE' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_bldc_motor',
    name: 'BLDC Motor',
    type: 'MOTOR_BLDC',
    category: 'MOTOR',
    description: 'Three-phase brushless motor load driven by an ESC',
    defaultProperties: {
      minimumSupplyVoltage: SIMULATION_MODELS.bldc.minimumSupplyVoltage,
      maximumRpm: SIMULATION_MODELS.bldc.maximumRpm,
      windingResistance: SIMULATION_MODELS.bldc.windingResistance,
    },
    pinConfig: { pinProfile: 'MOTOR_BLDC' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_buzzer',
    name: 'Buzzer',
    type: 'BUZZER',
    category: 'MOTOR',
    description: 'Current-driven buzzer with optional signal frequency',
    defaultProperties: { resistance: 42, frequency: SIMULATION_MODELS.audio.buzzerFrequencyHz },
    pinConfig: { pinProfile: 'BUZZER' },
    sortOrder: 7,
  }),
  makeComponent({
    id: 'catalog_push_button',
    name: 'Push Button',
    type: 'PUSH_BUTTON',
    category: 'PASSIVE',
    description: 'Momentary tactile switch',
    defaultProperties: { pressed: false },
    pinConfig: { pinProfile: 'PUSH_BUTTON' },
    sortOrder: 8,
  }),
  makeComponent({
    id: 'catalog_switch_spst',
    name: 'SPST Switch',
    type: 'SWITCH_SPST',
    category: 'PASSIVE',
    description: 'Latching single-pole single-throw switch',
    defaultProperties: { isClosed: false },
    pinConfig: { pinProfile: 'SWITCH_SPST' },
    sortOrder: 9,
  }),
  makeComponent({
    id: 'catalog_potentiometer',
    name: 'Potentiometer',
    type: 'POTENTIOMETER',
    category: 'PASSIVE',
    description: 'Three-terminal variable resistor',
    defaultProperties: { resistance: 10000, position: 0.5 },
    pinConfig: { pinProfile: 'POTENTIOMETER' },
    sortOrder: 10,
  }),
  ...([
    ['RELAY_SINGLE', 'Single Relay Module', 'RELAY', 'One-channel relay module with COM/NO/NC contacts'],
    ['RELAY_SPDT', 'SPDT Relay', 'RELAY', 'Bare SPDT relay with coil and changeover contacts'],
    ['RELAY_2CH', '2-Channel Relay Module', 'RELAY', 'Dual-channel relay module'],
    ['RELAY_4CH', '4-Channel Relay Module', 'RELAY', 'Four-channel relay module'],
  ] as const).map(([type, name, category, description], index) => makeComponent({
    id: `catalog_${type.toLowerCase()}`,
    name,
    type,
    category,
    description,
    defaultProperties: { triggerType: 'Active Low' },
    pinConfig: { pinProfile: type },
    sortOrder: 20 + index,
  })),
  ...([
    ['PIR_SENSOR', 'PIR Motion Sensor', 'SENSOR', { motionDetected: false }],
    ['SENSOR_PIR', 'PIR Motion Sensor', 'SENSOR', { motionDetected: false }],
    ['LDR', 'Photoresistor', 'SENSOR', { lightLevel: 50 }],
    ['SENSOR_LDR', 'Light Sensor', 'SENSOR', { lightLevel: 50 }],
    ['SOIL_MOISTURE', 'Soil Moisture Sensor', 'SENSOR', { moistureLevel: SIMULATION_MODELS.sensors.soilMoisture_percent }],
  ] as const).map(([type, name, category, defaultProperties], index) => makeComponent({
    id: `catalog_${type.toLowerCase()}`,
    name,
    type,
    category,
    description: `${name} with user-controlled environmental stimulus properties`,
    defaultProperties,
    pinConfig: { pinProfile: type },
    sortOrder: 40 + index,
  })),
  ...([
    ['LCD_16X2', 'LCD 16x2', 'DISPLAY'],
    ['DISPLAY_LCD_I2C', 'I2C LCD 16x2', 'DISPLAY'],
    ['OLED_DISPLAY', 'OLED Display', 'DISPLAY'],
    ['DISPLAY_OLED', 'I2C OLED Display', 'DISPLAY'],
    ['DISPLAY_7SEG', '7-Segment Display', 'DISPLAY'],
  ] as const).map(([type, name, category], index) => makeComponent({
    id: `catalog_${type.toLowerCase()}`,
    name,
    type,
    category,
    description: `${name} with power-aware visual output`,
    defaultProperties: {},
    pinConfig: { pinProfile: type },
    sortOrder: 60 + index,
  })),
  makeComponent({
    id: 'catalog_breadboard',
    name: 'Breadboard',
    type: 'BREADBOARD',
    category: 'PASSIVE',
    description: 'Half-size solderless breadboard with rails and terminal strips',
    defaultProperties: {},
    pinConfig: { pinProfile: 'BREADBOARD' },
    sortOrder: 10,
  }),
  makeComponent({
    id: 'catalog_555_timer',
    name: 'NE555 Timer',
    type: 'IC_555_TIMER',
    category: 'LOGIC',
    description: '555 timer IC for monostable and astable oscillator circuits',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP8', pinProfile: 'IC_555_TIMER' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_74hc595',
    name: '74HC595 Shift Register',
    type: 'IC_74HC595',
    category: 'LOGIC',
    description: '8-bit serial-in parallel-out shift register with output latches',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC595' },
    sortOrder: 2,
  }),
  makeComponent({
    id: 'catalog_74hc165',
    name: '74HC165 Shift Register',
    type: 'IC_74HC165',
    category: 'LOGIC',
    description: '8-bit parallel-in serial-out shift register',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC165' },
    sortOrder: 3,
  }),
  makeComponent({
    id: 'catalog_74hc138',
    name: '74HC138 3-to-8 Decoder',
    type: 'IC_74HC138',
    category: 'LOGIC',
    description: '3-to-8 line inverting decoder and demultiplexer',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC138' },
    sortOrder: 4,
  }),
  makeComponent({
    id: 'catalog_74hc151',
    name: '74HC151 8-Ch Multiplexer',
    type: 'IC_74HC151',
    category: 'LOGIC',
    description: '8-channel data selector and multiplexer',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_74HC151' },
    sortOrder: 5,
  }),
  makeComponent({
    id: 'catalog_cd4017',
    name: 'CD4017 Decade Counter',
    type: 'IC_CD4017',
    category: 'LOGIC',
    description: 'Johnson decade counter with 10 decoded outputs',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP16', pinProfile: 'IC_CD4017' },
    sortOrder: 6,
  }),
  makeComponent({
    id: 'catalog_multimeter',
    name: 'Digital Multimeter',
    type: 'MULTIMETER',
    category: 'INSTRUMENT',
    description: 'Dual-probe voltage, current, and resistance measurement tool',
    defaultProperties: { mode: 'VOLTAGE' },
    pinConfig: { footprint: 'MODULE', pinProfile: 'MULTIMETER' },
    sortOrder: 1,
  }),
  makeComponent({
    id: 'catalog_oscilloscope',
    name: 'Digital Oscilloscope',
    type: 'OSCILLOSCOPE',
    category: 'INSTRUMENT',
    description: '2-channel real-time waveform capture and frequency analyzer',
    defaultProperties: { timebase: '1ms', voltsPerDiv: 1.0 },
    pinConfig: { footprint: 'MODULE', pinProfile: 'OSCILLOSCOPE' },
    sortOrder: 2,
  }),

  // LED Family Variants
  makeComponent({
    id: 'catalog_led_red',
    name: 'Red LED',
    type: 'LED_RED',
    category: 'LED',
    description: 'Red indicator LED with diffused epoxy lens',
    defaultProperties: { ledColor: 'red', forwardVoltage: 2.0 },
    pinConfig: { pinProfile: 'LED_RED' },
    sortOrder: 10,
  }),
  makeComponent({
    id: 'catalog_led_green',
    name: 'Green LED',
    type: 'LED_GREEN',
    category: 'LED',
    description: 'Green indicator LED with diffused epoxy lens',
    defaultProperties: { ledColor: 'green', forwardVoltage: 2.2 },
    pinConfig: { pinProfile: 'LED_GREEN' },
    sortOrder: 11,
  }),
  makeComponent({
    id: 'catalog_led_blue',
    name: 'Blue LED',
    type: 'LED_BLUE',
    category: 'LED',
    description: 'Blue indicator LED with water-clear epoxy lens',
    defaultProperties: { ledColor: 'blue', forwardVoltage: 3.2 },
    pinConfig: { pinProfile: 'LED_BLUE' },
    sortOrder: 12,
  }),
  makeComponent({
    id: 'catalog_led_yellow',
    name: 'Yellow LED',
    type: 'LED_YELLOW',
    category: 'LED',
    description: 'Yellow indicator LED with diffused epoxy lens',
    defaultProperties: { ledColor: 'yellow', forwardVoltage: 2.1 },
    pinConfig: { pinProfile: 'LED_YELLOW' },
    sortOrder: 13,
  }),
  makeComponent({
    id: 'catalog_led_white',
    name: 'White LED',
    type: 'LED_WHITE',
    category: 'LED',
    description: 'Bright white indicator LED with water-clear epoxy lens',
    defaultProperties: { ledColor: 'white', forwardVoltage: 3.2 },
    pinConfig: { pinProfile: 'LED_WHITE' },
    sortOrder: 14,
  }),
  makeComponent({
    id: 'catalog_led_orange',
    name: 'Orange LED',
    type: 'LED_ORANGE',
    category: 'LED',
    description: 'Orange indicator LED with diffused epoxy lens',
    defaultProperties: { ledColor: 'orange', forwardVoltage: 2.0 },
    pinConfig: { pinProfile: 'LED_ORANGE' },
    sortOrder: 15,
  }),
  makeComponent({
    id: 'catalog_led_purple',
    name: 'Purple LED',
    type: 'LED_PURPLE',
    category: 'LED',
    description: 'Purple / UV indicator LED with diffused epoxy lens',
    defaultProperties: { ledColor: 'purple', forwardVoltage: 3.1 },
    pinConfig: { pinProfile: 'LED_PURPLE' },
    sortOrder: 16,
  }),

  // Logic Gate Family Variants (DIP-14)
  makeComponent({
    id: 'catalog_74hc00',
    name: '74HC00 Quad NAND',
    type: 'IC_74HC00',
    category: 'LOGIC',
    description: 'Quadruple 2-input positive-NAND gates in DIP-14 package',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC00' },
    sortOrder: 10,
  }),
  makeComponent({
    id: 'catalog_74hc04',
    name: '74HC04 Hex Inverter',
    type: 'IC_74HC04',
    category: 'LOGIC',
    description: 'Hex inverters in DIP-14 package',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC04' },
    sortOrder: 11,
  }),
  makeComponent({
    id: 'catalog_74hc08',
    name: '74HC08 Quad AND',
    type: 'IC_74HC08',
    category: 'LOGIC',
    description: 'Quadruple 2-input positive-AND gates in DIP-14 package',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC08' },
    sortOrder: 12,
  }),
  makeComponent({
    id: 'catalog_74hc32',
    name: '74HC32 Quad OR',
    type: 'IC_74HC32',
    category: 'LOGIC',
    description: 'Quadruple 2-input positive-OR gates in DIP-14 package',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC32' },
    sortOrder: 13,
  }),
  makeComponent({
    id: 'catalog_74hc86',
    name: '74HC86 Quad XOR',
    type: 'IC_74HC86',
    category: 'LOGIC',
    description: 'Quadruple 2-input exclusive-OR gates in DIP-14 package',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC86' },
    sortOrder: 14,
  }),
  makeComponent({
    id: 'catalog_74hc14',
    name: '74HC14 Hex Schmitt Inverter',
    type: 'IC_74HC14',
    category: 'LOGIC',
    description: 'Hex inverting Schmitt triggers with hysteresis in DIP-14 package',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC14' },
    sortOrder: 15,
  }),
  makeComponent({
    id: 'catalog_74hc74',
    name: '74HC74 Dual D Flip-Flop',
    type: 'IC_74HC74',
    category: 'LOGIC',
    description: 'Dual positive-edge-triggered D-type flip-flops with set and reset in DIP-14',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC74' },
    sortOrder: 16,
  }),
  makeComponent({
    id: 'catalog_74hc02',
    name: '74HC02 Quad NOR',
    type: 'IC_74HC02',
    category: 'LOGIC',
    description: 'Quadruple 2-input positive-NOR gates in DIP-14 package',
    defaultProperties: {},
    pinConfig: { footprint: 'DIP14', pinProfile: 'IC_74HC02' },
    sortOrder: 17,
  }),

  // Switch & Passive Variants
  makeComponent({
    id: 'catalog_switch_spdt',
    name: 'SPDT Switch',
    type: 'SWITCH_SPDT',
    category: 'PASSIVE',
    description: 'Single-pole double-throw slide switch with common and two positions',
    defaultProperties: { isClosed: false },
    pinConfig: { pinProfile: 'SWITCH_SPDT' },
    sortOrder: 21,
  }),
  makeComponent({
    id: 'catalog_toggle_switch',
    name: 'Toggle Switch',
    type: 'TOGGLE_SWITCH',
    category: 'PASSIVE',
    description: 'Heavy-duty panel-mount SPDT toggle switch with metal bat actuator',
    defaultProperties: { isClosed: false },
    pinConfig: { pinProfile: 'TOGGLE_SWITCH' },
    sortOrder: 22,
  }),
  makeComponent({
    id: 'catalog_dip_switch_4',
    name: '4-Position DIP Switch',
    type: 'DIP_SWITCH_4',
    category: 'PASSIVE',
    description: 'Four independent SPST slide switches in an 8-pin DIP package',
    defaultProperties: { sw1: false, sw2: false, sw3: false, sw4: false },
    pinConfig: { pinProfile: 'DIP_SWITCH_4' },
    sortOrder: 23,
  }),
  makeComponent({
    id: 'catalog_trimpot',
    name: 'Trimpot',
    type: 'TRIMPOT',
    category: 'PASSIVE',
    description: 'Precision horizontal trimmer potentiometer with adjustment screw',
    defaultProperties: { resistance: 10000, position: 0.5 },
    pinConfig: { pinProfile: 'TRIMPOT' },
    sortOrder: 24,
  }),
  makeComponent({
    id: 'catalog_photo_diode',
    name: 'Photodiode',
    type: 'PHOTO_DIODE',
    category: 'PASSIVE',
    description: 'High-speed optical photosensor diode in a 5mm clear package',
    defaultProperties: { lightLevel: 50 },
    pinConfig: { pinProfile: 'PHOTO_DIODE' },
    sortOrder: 25,
  }),

  // Instrument Family Variants
  makeComponent({
    id: 'catalog_voltmeter',
    name: 'Digital Voltmeter',
    type: 'VOLTMETER',
    category: 'INSTRUMENT',
    description: 'Digital LED panel meter for measuring DC voltage',
    defaultProperties: { mode: 'VOLTAGE' },
    pinConfig: { footprint: 'MODULE', pinProfile: 'VOLTMETER' },
    sortOrder: 10,
  }),
  makeComponent({
    id: 'catalog_logic_analyzer',
    name: 'Logic Analyzer',
    type: 'LOGIC_ANALYZER',
    category: 'INSTRUMENT',
    description: '8-channel USB digital logic analyzer (up to 24MHz)',
    defaultProperties: { sampleRate: '24MHz' },
    pinConfig: { footprint: 'MODULE', pinProfile: 'LOGIC_ANALYZER' },
    sortOrder: 11,
  }),

  // Power Family Variants
  makeComponent({
    id: 'catalog_battery_18650',
    name: '18650 Li-Ion Cell',
    type: 'BATTERY_18650',
    category: 'POWER',
    description: 'Rechargeable 3.7V 2500mAh cylindrical lithium-ion cell',
    defaultProperties: { voltage: 3.7, isOn: true },
    pinConfig: { pinProfile: 'BATTERY_18650' },
    sortOrder: 20,
  }),
  makeComponent({
    id: 'catalog_battery_cr2032',
    name: 'CR2032 Coin Cell',
    type: 'BATTERY_CR2032',
    category: 'POWER',
    description: '3V lithium button cell battery for low-power electronics',
    defaultProperties: { voltage: 3.0, isOn: true },
    pinConfig: { pinProfile: 'BATTERY_CR2032' },
    sortOrder: 21,
  }),
  makeComponent({
    id: 'catalog_battery_lipo',
    name: 'LiPo Battery',
    type: 'BATTERY_LIPO',
    category: 'POWER',
    description: 'Single-cell 3.7V 500mAh lithium-polymer pouch battery with protection circuit',
    defaultProperties: { voltage: 3.7, isOn: true },
    pinConfig: { pinProfile: 'BATTERY_LIPO' },
    sortOrder: 22,
  }),
  makeComponent({
    id: 'catalog_battery_aaa',
    name: 'AAA Battery',
    type: 'BATTERY_AAA',
    category: 'POWER',
    description: 'Standard 1.5V alkaline AAA cell with positive and negative terminals',
    defaultProperties: { voltage: 1.5, isOn: true },
    pinConfig: { pinProfile: 'BATTERY_AAA' },
    sortOrder: 23,
  }),
  makeComponent({
    id: 'catalog_regulator_ams1117',
    name: 'AMS1117 3.3V Regulator',
    type: 'VOLTAGE_REGULATOR_AMS1117',
    category: 'POWER',
    description: 'Low-dropout (LDO) 3.3V linear voltage regulator module',
    defaultProperties: { voltage: 3.3 },
    pinConfig: { pinProfile: 'VOLTAGE_REGULATOR_AMS1117' },
    sortOrder: 24,
  }),

  // Sensor Family Variants
  makeComponent({
    id: 'catalog_ultrasonic_sensor',
    name: 'HC-SR04 Ultrasonic Sensor',
    type: 'ULTRASONIC_SENSOR',
    category: 'SENSOR',
    description: 'Dual-transducer ultrasonic distance measurement sensor (2cm–400cm)',
    defaultProperties: { distance_cm: 25 },
    pinConfig: { pinProfile: 'ULTRASONIC_SENSOR' },
    sortOrder: 50,
  }),
  makeComponent({
    id: 'catalog_temperature_sensor',
    name: 'DHT11 Temp & Humidity',
    type: 'TEMPERATURE_SENSOR',
    category: 'SENSOR',
    description: 'Digital composite temperature and relative humidity sensor',
    defaultProperties: { temperature_C: 24, humidity_percent: 50 },
    pinConfig: { pinProfile: 'TEMPERATURE_SENSOR' },
    sortOrder: 51,
  }),
  makeComponent({
    id: 'catalog_tmp36',
    name: 'TMP36 Temp Sensor',
    type: 'TMP36',
    category: 'SENSOR',
    description: 'Precision analog linear temperature sensor in TO-92 package (10mV/°C)',
    defaultProperties: { temperature_C: 25 },
    pinConfig: { pinProfile: 'TMP36' },
    sortOrder: 52,
  }),
  makeComponent({
    id: 'catalog_gas_sensor',
    name: 'MQ-2 Gas Sensor',
    type: 'GAS_SENSOR',
    category: 'SENSOR',
    description: 'Semiconductor gas sensor for smoke, LPG, methane, and butane detection',
    defaultProperties: { gasLevel_ppm: 100 },
    pinConfig: { pinProfile: 'GAS_SENSOR' },
    sortOrder: 53,
  }),

  // Motor & Actuator Family Variants
  makeComponent({
    id: 'catalog_vibration_motor',
    name: 'Vibration Motor',
    type: 'VIBRATION_MOTOR',
    category: 'MOTOR',
    description: 'Compact coin-type eccentric mass haptic feedback vibration motor',
    defaultProperties: { ratedVoltage: 3.0 },
    pinConfig: { pinProfile: 'VIBRATION_MOTOR' },
    sortOrder: 20,
  }),
  makeComponent({
    id: 'catalog_gear_motor',
    name: 'TT Gear Motor',
    type: 'GEAR_MOTOR',
    category: 'MOTOR',
    description: 'Dual-shaft 1:48 reduction gearbox DC hobby motor',
    defaultProperties: { ratedVoltage: 6.0, gearRatio: 48 },
    pinConfig: { pinProfile: 'GEAR_MOTOR' },
    sortOrder: 21,
  }),
  makeComponent({
    id: 'catalog_solenoid',
    name: 'Linear Solenoid',
    type: 'SOLENOID',
    category: 'MOTOR',
    description: 'Open-frame 12V electromagnetic push-pull linear actuator',
    defaultProperties: { ratedVoltage: 12.0 },
    pinConfig: { pinProfile: 'SOLENOID' },
    sortOrder: 22,
  }),

  // Display Family Variants
  makeComponent({
    id: 'catalog_7seg_4digit',
    name: '4-Digit 7-Segment (TM1637)',
    type: 'DISPLAY_7SEG_4DIGIT',
    category: 'DISPLAY',
    description: 'Four-digit seven-segment LED display module with TM1637 driver',
    defaultProperties: {},
    pinConfig: { pinProfile: 'DISPLAY_7SEG_4DIGIT' },
    sortOrder: 70,
  }),
  makeComponent({
    id: 'catalog_led_bar_graph',
    name: '10-Segment LED Bar',
    type: 'LED_BAR_GRAPH',
    category: 'DISPLAY',
    description: 'Ten-element multi-color (green/yellow/red) LED bar graph array',
    defaultProperties: {},
    pinConfig: { pinProfile: 'LED_BAR_GRAPH' },
    sortOrder: 71,
  }),
  makeComponent({
    id: 'catalog_max7219_matrix',
    name: 'MAX7219 8x8 LED Matrix',
    type: 'DISPLAY_MAX7219_MATRIX',
    category: 'DISPLAY',
    description: 'Serial-interfaced 8x8 red LED dot matrix module with MAX7219 driver',
    defaultProperties: {},
    pinConfig: { pinProfile: 'DISPLAY_MAX7219_MATRIX' },
    sortOrder: 72,
  }),

  // Relay Family Variants
  makeComponent({
    id: 'catalog_relay_8ch',
    name: '8-Channel Relay Module',
    type: 'RELAY_8CH',
    category: 'RELAY',
    description: 'Eight-channel optocoupler-isolated 5V relay module with screw terminals',
    defaultProperties: { triggerType: 'Active Low' },
    pinConfig: { pinProfile: 'RELAY_8CH' },
    sortOrder: 30,
  }),
  makeComponent({
    id: 'catalog_relay_ssr',
    name: 'Solid State Relay (SSR-40DA)',
    type: 'RELAY_SSR',
    category: 'RELAY',
    description: 'Industrial 40A solid-state relay with 3-32VDC input and 24-380VAC output',
    defaultProperties: { triggerType: 'DC-AC' },
    pinConfig: { pinProfile: 'RELAY_SSR' },
    sortOrder: 31,
  }),
];

const builtinByType = new Map(builtinCanvasComponents.map((component) => [component.type, component]));

export function findCatalogComponent(type: string): ElectronicComponent | undefined {
  return builtinByType.get(type);
}

export function mergeComponentLibrary(apiComponents: ElectronicComponent[] = []): ElectronicComponent[] {
  const byType = new Map<string, ElectronicComponent>();
  builtinCanvasComponents.forEach((component) => byType.set(component.type, component));
  apiComponents.forEach((component) => byType.set(component.type, component));
  return Array.from(byType.values());
}
